[theme]
primaryColor = "#8d4bff"        # Color de los botones y acentos
backgroundColor = "#171a22"     # Color de fondo (oscuro en este caso)
secondaryBackgroundColor = "#262a36" # Color de las cajas de entrada
textColor = "#FAFAFA"           # Color del texto
font = "sans serif"             # Tipo de letra

#[client]
#toolbarMode = "hidden"
